SET HOME=.
SET BIN=%HOME%\bin
SET SRC=%HOME%\src
SET SRCLIST=~srclist.txt
SET JARNAME=BASICCompiler.jar
SET MANIFESTNAME=manifest.txt
PUSHD .
IF EXIST %BIN% RMDIR /S %BIN%
MKDIR %BIN%
IF EXIST %SRCLIST% DEL %SRCLIST%
DIR /S /B /A-D %SRC% | FINDSTR /V /C:tests > %SRCLIST%
%JAVA_HOME%\bin\javac -d %BIN% @%SRCLIST%
DEL %SRCLIST%
COPY %MANIFESTNAME% %BIN%
CD %BIN%
IF EXIST %JARNAME% DEL %JARNAME%
%JAVA_HOME%\bin\jar cfm %JARNAME% %MANIFESTNAME% *
DEL %MANIFESTNAME%
POPD
MOVE %BIN%\%JARNAME% .
